export default {
    emailRegex: /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i,
    // REACT_APP_BASE_URL : 'http://113.161.79.146:5001',
    REACT_APP_BASE_URL: 'https://ntvsolar.indedg.com:5005',
    CONTACT_INFO: {
        address: '49/13 Hoàng Dư Khương, P.12, Q.10, TP. Hồ Chí Minh',
        phone: '(+84) 902 586 121',
        email: 'ntvsolar@gmail.com'
    },
    DEVICE_TAG_NAME: {
        manufacturer: 'Nhà sản xuất',
        model: 'model',
        version: 'version',
        sn: 'Serial Number',
        deviceAddress: 'Địa chỉ thiết bị',
        AmpsA: 'Dòng điện pha A',
        AmpsB: 'Dòng điện pha B',
        AmpsC: 'Dòng điện pha C',
        VoltAN: 'Điện áp pha A',
        VoltBN: 'Điện áp pha B',
        VoltCN: 'Điện áp pha C',
        Watts: 'Công suất hiệu dụng (công suất thực)',
        Hz: 'Tần số lưới điện',
        VA: 'Công suất biểu kiến',
        VAr: 'Công suất phản kháng',
        PF: 'Hệ số công suất (cos phi)',
        WH: 'Tổng lượng điện phát',
        DCAmps: 'Tổng dòng điện DC',
        DCVolt: 'Điện áp DC',
        DCWatts: 'Tổng công suất DC',
        tmpCab: 'Nhiệt độ bên trong inverter',
        operatingState: 'Trạng thái hoạt động',
        WattsMax: 'Giới hạn công suất',
        VoltRef: 'Điện áp tham chiếu',
        nameplateWatts: 'Công suất danh định',
    }
};